### ISSUE TITLE
Better error message in stack alloc for stack ptr

### ISSUE THREAD

**Issue by sarranz** [jasmin-lang/jasmin#843]
This program
```
export fn main() -> () {
    stack u64 x;
    x = 0;
    [x] = 0;
}
```
gives
```
compilation error in function main:
stack allocation: x (defined at "ble.jazz", line 3 (4-5)) is a stack variable,
but a reg variable is expected
```
which makes sense.

But this one
```
export fn main() -> reg u64 {
    stack u64[1] a;
    stack ptr u64[1] pa;
    pa = a;
    pa[0] = 0;
    reg u64 r;
    r = pa[0];
    return r;
}
```
gives
```
compilation error in function main:
stack allocation: pa (defined at "ble.jazz", line 4 (4-6)) is a stack pointer, it should
not appear in an expression
```
where it's not clear that the problem is that it is `stack` instead of `reg`, and also not clear where the expression part comes from (I can't tell from the code either). Doesn't the first error message work for both cases?

**Comment by vbgl** [comment]
Note that the first program now leads to an internal error:

~~~
line 4 (4-12):
internal compilation error in function main:
  linearization: check_lexpr
~~~

Stack-allocation is happy to nest memory accesses:
~~~
  [:u64 [#aligned :u64 RSP.61 +64u (64u) 0]] = #MOV_64((64u) 0);
~~~

**Comment by vbgl** [comment]
Regression introduced in #1151.
